CREATE TYPE "public"."yes_no" AS ENUM('예', '아니오');--> statement-breakpoint
CREATE TABLE "patents" (
	"patent_id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "patents_patent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"our_ref" text NOT NULL,
	"status" text NOT NULL,
	"application_type" text NOT NULL,
	"applicant_name" text,
	"filing_date" timestamp,
	"application_number" text,
	"title_kr" text,
	"applicant_reference" text,
	"registration_date" timestamp,
	"registration_number" text,
	"examination_requested_at" timestamp,
	"examination_request_due" timestamp,
	"annuity_due_date" timestamp,
	"attorney_name" text,
	"abandonment_date" timestamp,
	"abandonment_reason" text,
	"pct_application_number" text,
	"pct_application_date" timestamp,
	"priority_date" timestamp,
	"request_date" timestamp,
	"filing_deadline" timestamp,
	"title_en" text,
	"claims_due_date" timestamp,
	"claims_submitted_at" timestamp,
	"publication_date" timestamp,
	"publication_number" text,
	"decision_to_register_date" timestamp,
	"registration_deadline" timestamp,
	"late_registration_penalty_due" timestamp,
	"protection_term" text,
	"is_annuity_managed" boolean,
	"inventor" text,
	"assignee" text,
	"earliest_priority_date" timestamp,
	"expedited_examination_requested" boolean,
	"expedited_examination_date" timestamp,
	"examination_requested" "yes_no",
	"priority_claimed" "yes_no",
	"priority_rights" jsonb,
	"metadata" jsonb,
	"user_id" uuid,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "patents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "patents" ADD CONSTRAINT "patents_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE POLICY "select-patent-policy" ON "patents" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) = "patents"."user_id");